GET http://localhost:3011/api/activities

###

POST http://localhost:3011/api/activities
Content-Type: application/json

{
    "name": "Zoolabo",
    "description": "steochondropathy",
    "category": "social",
    "action_field": "rutrum",
    "involved_group": "ac",
    "location": "578 Fair Oaks Court",
    "start_date": "2022-05-26",
    "end_date": "2023-12-21",
    "modality": "presencial",
    "min_members": 22,
    "max_members": 75,
    "sponsor_id": 1
}

###

GET http://localhost:3011/api/activities/3

###

PUT http://localhost:3011/api/activities/3
Content-Type: application/json

{
    "name": "sadfsdassasdadasd",
    "description": "steochondropathy",
    "category": "medioambiental",
    "action_field": "rutrum",
    "involved_group": "ac",
    "location": "578 Fair Oaks Court",
    "start_date": "2022-05-26",
    "end_date": "2023-12-21",
    "modality": "presencial",
    "min_members": 22,
    "max_members": 75,
    "sponsor_id": 2
}

###

DELETE http://localhost:3011/api/activities/2
###

GET http://localhost:3011/api/activities/sponsor/1