GET http://localhost:3011/api/administrators

###
GET http://localhost:3011/api/administrators/2

###

POST http://localhost:3011/api/administrators
Content-Type: application/json

{
    "user": "Alex",
    "email": "marcos.ortiz@live.u-tad.com",
    "phone": 717712185
}

###

PUT http://localhost:3011/api/administrators/2
Content-Type: application/json

{
    "user": "JoseMaria",
    "email": "marcos.ortiz@live.u-tad.com",
    "phone": 717712185
}


###
DELETE http://localhost:3011/api/administrators/1
