POST http://localhost:3000/api/auth/register/member
Content-Type: application/json

{
    "first_name": "Alejandro",
    "last_name": "Escudero",
    "email": "alex@gmail.com",
    "password": "pass1",
    "phone": "123456789",
    "birth_date": "1995-06-15",
    "bith_date": "1995-06-15",
    "dni": "54367567H",
    "genre": "male",
    "studies": "INSO"
}

###LOGIN DE UN MIEMBRO
POST http://localhost:3000/api/auth/login/member
Content-Type: application/json

{
    "email": "alex@gmail.com",
    "password": "pass1"
}