### Un usuario no registrado debería poder ver todas las actividades
GET http://localhost:3011/api/activities

### Un usuario no registrado podrá ver los detalles de una actividad concreta
GET http://localhost:3011/api/activities/1



########################################################################################
###################     HISTORIAS DE USUARIOS REGISTRADOS ##############################
########################################################################################

### Un usuario no registrado deberá poder registrarse  y obtener su token, a su vez creará sus preferencias
POST http://localhost:3011/api/auth/register/member HTTP/1.1
Content-Type: application/json

{
    "member": {
        "first_name": "Pepito",
        "last_name": "Castel",
        "email": "Pepito@gmail.com",
        "password": "password1",
        "phone": "123496789",
        "birth_date": "1995-06-15",
        "dni": "57090987H",
        "gender": "male",
        "degree": "INSO"
    },
    "preferences": {
        "category": "medioambiental",
        "modality": "online",
        "availability": "total",
        "commitment_estimate": "total"
    }
}

### Se deberían poder editar preferencias: NO

### Un usuario registrado deberá poder hacer login y obtener su token
POST http://localhost:3011/api/auth/login/member HTTP/1.1
Content-Type: application/json

{
    "email": "joret@gmail.com",
    "password": "password1"
}

### Un usuario registrado deberá poder editar su propio usuario
PUT http://localhost:3011/api/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE2ODU0NjYzNjMsImV4cCI6MTY4NTQ3MzU2M30.WqQrT8pm9AiR_nvRcLPLC0wQe4qcX2fK-3rs3TXDFeE

{
    "first_name": "Pepito",
    "last_name": "Castelo",
    "email": "Pepito@gmail.com",
    "password": "password1",
    "phone": "123496789",
    "birth_date": "1995-06-15",
    "dni": "57090987H",
    "gender": "male",
    "degree": "INSO"
}


### Un usuario registrado podrá apuntarse a una actividad haciendo un post a la tabla de participation
POST http://localhost:3011/api/participation/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE2ODU0NjYzNjMsImV4cCI6MTY4NTQ3MzU2M30.WqQrT8pm9AiR_nvRcLPLC0wQe4qcX2fK-3rs3TXDFeE

### Un usuario registrado podrá darse de baja de una actividad
DELETE http://localhost:3011/api/participation/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6Im1lbWJlciIsImlhdCI6MTY4MzgzMTY3OCwiZXhwIjoxNjgzODM4ODc4fQ.Qxa8h2jjg8jWzM3ppyAGHjc2lqqMNgbNnRPmibkUIJk






########################################################################################
###################     HISTORIAS DE ADMINISTRADORES ###################################
########################################################################################

### Un administrador deberá poder registar su usuario 
POST http://localhost:3011/api/auth/register/admin
Content-Type: application/json

{
    "user": "Admin3",
    "email": "admin3@live.u-tad.com",
    "phone": 717712185
}

### Un administrador deberá poder registrar a un sponsor con su token y devolverle el token del sponsor, que no caducará
POST http://localhost:3011/api/auth/register/sponsor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1NDY2NDQyfQ.A4yVgLCD2bL1hCcFImf8eG_Uun7BDycm_4NuW8fl0qs

{
    "entity": "Oracle",
    "user": "Pere",
    "password": "1234",
    "email": "prpe.perez@u-tad.com"
}

### Un administrador deberá poder dar de baja a un sponsor
DELETE http://localhost:3011/api/auth/delete/sponsor/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgzODMxNzA3fQ.dvlKeMj7F6xus1VdZTyyyHEf2DLwAstK2lx0vmZO4Ys














### Un sponsor deberá poder crear una actividad con su token de sponsor
POST http://localhost:3011/api/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InNwb25zb3IiLCJpYXQiOjE2ODU0NjY0NTksImV4cCI6MTY4NTQ3MzY1OX0.sCI_bJ933-zHOijV2OnwGQcO7RgxuwUeOPE2VYsau3I

{
    "name": "PruebaActividad",
    "description": "steochondropathy",
    "category": "social",
    "action_field": "rutrum",
    "involved_group": "ac",
    "location": "578 Fair Oaks Court",
    "start_date": "2022-05-26",
    "end_date": "2023-12-21",
    "modality": "presencial",
    "min_members": 22,
    "max_members": 75
}

### Un sponsor deberá tener acceso a los usuarios inscritos a una actividad


###

