
GET http://localhost:3000
###
GET http://localhost:3000/api/members
###
GET http://localhost:3000/api/members/1

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    "first_name": "Alejandro",
    "last_name": "Escudero",
    "email": "alex@gmail.com",
    "password": "pass1",
    "phone": "123456789"
}

###

GET http://localhost:3000/api/preferences/2

###

POST http://localhost:3000/api/preferences
Content-Type: application/json

{
    "category": "medioambiental",
    "modality": "online",
    "availability": "total",
    "commitment_estimate": "total",
    "member_id": 1
}

###

DELETE http://localhost:3000/api/preferences/1